export const GALLERY_CATEGORIES = [
  "All",
  "Workshops",
  "Hackathons",
  "Talks",
  "Community",
  "Labs",
];

export const galleryPhotos = [
  {
    id: "g-01",
    aspect: "3 / 4",
    src: "https://images.unsplash.com/photo-1531482615713-2afd69097998?q=80&w=900&h=1200&fit=crop&auto=format",
    title: "First AWS workshop on campus",
    event: "Cloud Kickoff Workshop",
    category: "Workshops",
    date: "2025-08-16",
    location: "Innovation Block, GITS",
    photographer: "Club Media Team",
    featured: true,
  },
  {
    id: "g-02",
    aspect: "4 / 5",
    src: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=900&auto=format&fit=crop",
    title: "Builders around the whiteboard",
    event: "Architecture Lab",
    category: "Labs",
    date: "2025-09-04",
    location: "Lab 3, GITS",
    photographer: "Club Media Team",
    featured: true,
  },
  {
    id: "g-03",
    aspect: "5 / 4",
    src: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=1400&auto=format&fit=crop",
    title: "Overnight hackathon floor",
    event: "Cloud Resilience Hackathon",
    category: "Hackathons",
    date: "2025-10-12",
    location: "Main Auditorium Foyer",
    photographer: "Club Media Team",
    featured: true,
  },
  {
    id: "g-04",
    aspect: "2 / 3",
    src: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=1000&auto=format&fit=crop",
    title: "Keynote lighting the hall",
    event: "Expert Lecture: IAM & Security",
    category: "Talks",
    date: "2025-11-08",
    location: "Main Auditorium, GITS",
    photographer: "Club Media Team",
    featured: true,
  },
  {
    id: "g-05",
    aspect: "1 / 1",
    src: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1100&auto=format&fit=crop",
    title: "Squad shipping a lab together",
    event: "Hands-on Lambda Lab",
    category: "Labs",
    date: "2026-01-18",
    location: "Innovation Block, GITS",
    photographer: "Club Media Team",
    featured: true,
  },
  {
    id: "g-06",
    aspect: "3 / 5",
    src: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?q=80&w=800&auto=format&fit=crop",
    title: "Community meetup after hours",
    event: "Builder Circle",
    category: "Community",
    date: "2026-02-07",
    location: "Campus courtyard",
    photographer: "Club Media Team",
    featured: true,
  },
  {
    id: "g-07",
    aspect: "4 / 3",
    src: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?q=80&w=1200&auto=format&fit=crop",
    title: "Mentors walking the floor",
    event: "Office Hours",
    category: "Community",
    date: "2026-02-21",
    location: "Club room, GITS",
    photographer: "Club Media Team",
    featured: false,
  },
  {
    id: "g-08",
    aspect: "5 / 7",
    src: "https://images.unsplash.com/photo-1517048676732-d65bc937f952?q=80&w=900&auto=format&fit=crop",
    title: "Certificate wrap-up",
    event: "Cloud Kickoff Workshop",
    category: "Workshops",
    date: "2025-08-16",
    location: "Innovation Block, GITS",
    photographer: "Club Media Team",
    featured: true,
  },
  {
    id: "g-09",
    aspect: "9 / 16",
    src: "https://images.unsplash.com/photo-1553877522-43269d4ea984?q=80&w=700&auto=format&fit=crop",
    title: "Demo day on the big screen",
    event: "Cloud Resilience Hackathon",
    category: "Hackathons",
    date: "2025-10-12",
    location: "Main Auditorium, GITS",
    photographer: "Club Media Team",
    featured: false,
  },
  {
    id: "g-10",
    aspect: "5 / 4",
    src: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=1300&auto=format&fit=crop",
    title: "Laptops, cables, and cloud consoles",
    event: "Hands-on Lambda Lab",
    category: "Labs",
    date: "2026-01-18",
    location: "Lab 3, GITS",
    photographer: "Club Media Team",
    featured: true,
  },
  {
    id: "g-11",
    aspect: "3 / 4",
    src: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?q=80&w=800&auto=format&fit=crop",
    title: "Q&A with the visiting speaker",
    event: "Expert Lecture: IAM & Security",
    category: "Talks",
    date: "2025-11-08",
    location: "Main Auditorium, GITS",
    photographer: "Club Media Team",
    featured: false,
  },
  {
    id: "g-12",
    aspect: "4 / 5",
    src: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?q=80&w=1100&auto=format&fit=crop",
    title: "Group photo after the session",
    event: "Builder Circle",
    category: "Community",
    date: "2026-02-07",
    location: "Campus courtyard",
    photographer: "Club Media Team",
    featured: true,
  },
  {
    id: "g-13",
    aspect: "2 / 3",
    src: "https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=1000&auto=format&fit=crop",
    title: "Team huddle before the pitch",
    event: "Cloud Resilience Hackathon",
    category: "Hackathons",
    date: "2025-10-13",
    location: "Innovation Block, GITS",
    photographer: "Club Media Team",
    featured: false,
  },
  {
    id: "g-14",
    aspect: "1 / 1",
    src: "https://images.unsplash.com/photo-1591115765373-5207764f72e7?q=80&w=750&auto=format&fit=crop",
    title: "Live architecture walkthrough",
    event: "Architecture Lab",
    category: "Labs",
    date: "2025-09-04",
    location: "Lab 3, GITS",
    photographer: "Club Media Team",
    featured: false,
  },
  {
    id: "g-15",
    aspect: "3 / 5",
    src: "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?q=80&w=1200&auto=format&fit=crop",
    title: "Hall filling up for Community Day prep",
    event: "Community Day Planning Meet",
    category: "Talks",
    date: "2026-03-02",
    location: "Main Auditorium, GITS",
    photographer: "Club Media Team",
    featured: false,
  },
  {
    id: "g-16",
    aspect: "4 / 3",
    src: "https://images.unsplash.com/photo-1524178232363-1fb2b075b955?q=80&w=850&auto=format&fit=crop",
    title: "New members induction",
    event: "Builder Circle",
    category: "Community",
    date: "2026-03-14",
    location: "Club room, GITS",
    photographer: "Club Media Team",
    featured: false,
  },
];

export const galleryEvents = [
  ...new Set(galleryPhotos.map((p) => p.event)),
];

export function featuredGalleryPhotos(limit = 9) {
  return galleryPhotos.filter((p) => p.featured).slice(0, limit);
}

export function filterGallery(photos, { category = "All", event = "All", sort = "newest" } = {}) {
  let next = photos;
  if (category && category !== "All") {
    next = next.filter((p) => p.category === category);
  }
  if (event && event !== "All") {
    next = next.filter((p) => p.event === event);
  }
  next = [...next].sort((a, b) => {
    const da = new Date(a.date).getTime();
    const db = new Date(b.date).getTime();
    return sort === "oldest" ? da - db : db - da;
  });
  return next;
}
