// Home page core team
export const coreTeamMembers = [
  {
    id: "captain",
    name: "Manish Sahu",
    role: "Captain",
    band: "Leadership",
    photo: "/team/t1.jpeg",
    intro:
      "Leads AWS Student Builder Club at GITS. Sets the year plan, represents the club with faculty and AWS community partners, and keeps sessions shipping on campus.",
    position: "Captain, AWS Student Builder Club · GITS",
    field: "Devops engineer at Dhinex",
    qualifications: [
      "B.Tech CSE, Geetanjali Institute of Technical Studies",
      "AWS Cloud Practitioner",
      "Redhat Certified System Administrator (RHCSA)",
      "Microsoft Azure Fundamentals (AZ-900)",
    ],
    achievements: [
      "Hack-it-Sapiens Hackathon Winner — 2024 • Codefiesta 3.0",
      "Hackathon Winner — 2024 (IEEE) and Internal SIH Winner — 2024",
      "Mentored first-year builders through IAM and VPC labs",
    ],
    experience: [
      {
        title: "Captain",
        org: "AWS Student Builder Club, GITS",
        period: "2025 — present",
      },
      {
        title: "DevOps Engineer ",
        org: "Dhinex Pvt. Ltd.",
        period: "2026 — Present",
      },
    ],
    technologies: [
      "C",
      "C++",
      "Python",
      "MySQL",
      "AWS",
      "Terraform",
      "Boto3",
      "scikit-learn",
      "pandas",
      "Ansible",
      "Git",
      "GitHub",
      "Kubernetes",
      "Docker",
      "Linux System Administration",
      "GitHub Actions",
      "Fastlane",
      "Azure",
      "OpenTofu",
      "Terragrunt",
      "n8n",
      "Jenkins",
    ],
    fact: "Keeps a paper notebook of every lab that broke in production — and how the team fixed it.",
    linkedin: "https://www.linkedin.com/in/manish-sahu99/",
  },
  {
    id: "vice-captain",
    name: "Mahak Rahi",
    role: "Vice Captain",
    band: "Leadership",
    photo: "team/t4.jpeg",
    intro:
      "Passionate Computer Science student with hands-on experience in AWS Cloud and DevOps practices",
    position: "Vice Captain, AWS Student Builder Club · GITS",
    field: "Junior DevOps Engineer",
    qualifications: [
      "B.Tech IT, Geetanjali Institute of Technical Studies",
      "AWS Cloud Practitioner",
      "Redhat Certified System Administrator (RHCSA)",
      "Redhat Certified Engineer (RHCE)",
    ],
    achievements: [
      "Core member AWS ACADEMY X GITS CHAPTER",
      "SMART INDIA HACKATHON 2024 (Hardware Edition) WINNER (5 days)",
      "3x State level Hackathon Winner",
    ],
    experience: [
      {
        title: "Vice Captain",
        org: "AWS Student Builder Club, GITS",
        period: "2025 — present",
      },
      {
        title: "Junior DevOps Engineer",
        org: "Dhinex",
        period: "May 2026 — Present",
      },
    ],
    technologies: [
      "AWS",
      "Notion",
      "Jenkins",
      "Ansible",
      "Docker",
      "Kubernetes",
      "Prometheus",
      "Grafana",
      "Git",
      "Github",
      "Terraform",
      "Linux (RHEL)",
    ],
    fact: "Can explain VPC peering using only a cafeteria napkin and two chai cups.",
    linkedin: "https://www.linkedin.com/in/mahak-rahi/",
  },
  {
    id: "Tech Lead Cloud Infra",
    name: "Bhavesh Suthar",
    role: "Tech Lead Cloud Infra",
    band: "Tech",
    photo: "/team/t3.png",
    intro:
      "I work at the intersection of cloud infrastructure, networking, and DevOps, leading hands-on AWS initiatives at the AWS Student Builder Club, GITS. My focus is on making cloud learning practical — from deploying real workloads to understanding the infrastructure behind them.",
    position: "Tech Lead (Cloud Infra), AWS Student Builder Club · GITS",
    field: "Fullstack Developer",
    qualifications: [
      "B.Tech CSE, GITS (3rd Year)",
      "Redhat Certified System Administrator (RHCSA)",
    ],
    achievements: [
      "1st Runner-Up, CodeFiesta Hackathon 4.0, GIT Jaipur (2025)",
      "Runner-Up, Internal SIH – AI-based soluti",
    ],
    experience: [
      {
        title: "Tech Lead — Cloud",
        org: "AWS Student Builder Club, GITS",
        period: "2025 — present",
      },
      {
        title: "Full Stack Developer Intern",
        org: "Toba Tech Solutions, Udaipur",
        period: "Aug 2026 – Sep 2026",
      },
    ],
    technologies: [
      "JavaScript",
      "TypeScript",
      "C++",
      "C",
      "Java",
      "React.js",
      "Next.js",
      "Tailwind CSS",
      "Node.js",
      "Express.js",
      "NestJS",
      "REST APIs",
      "TypeORM",
      "Mongoose",
      "Firebase",
      "MongoDB",
      "PostgreSQL",
      "DSA",
      "Git",
      "GitHub",
      "AWS",
      "Linux",
      "Terraform",
      "Docker",
    ],
    fact: "In AWS, always check your Free Tier limits and set billing alerts before experimenting with new services.",
    linkedin: "https://www.linkedin.com/in/bhavesh-suthar-048587332/",
  },
  {
    id: "Tech Lead",
    name: "Sohail Ansari",
    role: "Tech Lead",
    band: "Tech",
    photo: "/team/t2.jpeg",
    intro:
      "Owns the AI and application track — Bedrock, Lambda backends, and the student projects that sit on top of AWS.",
    position: "Tech Lead (AI & Apps), AWS Student Builder Club · GITS",
    field: "Applied AI and serverless applications",
    qualifications: [
      "B.Tech CSE (AI), GITS",
      "AWS AI Practitioner",
      "DeepLearning.AI short course",
    ],
    achievements: [
      "Shipped the club’s first Bedrock agent workshop",
      "Mentored the winning hackathon team on RAG basics",
      "Published internal notes that new members still reuse",
    ],
    experience: [
      {
        title: "Tech Lead — AI & Apps",
        org: "AWS Student Builder Club, GITS",
        period: "2025 — present",
      },
      { title: "Research intern", org: "Campus AI cell", period: "2024" },
    ],
    technologies: [
      "AWS Bedrock",
      "Lambda",
      "API Gateway",
      "Python",
      "React",
      "DynamoDB",
    ],
    fact: "Tests every demo prompt on a phone with a weak campus Wi-Fi signal first.",
    linkedin: "https://www.linkedin.com/in/sohailansari163/",
  },
  {
    id: "outreach",
    name: "Daksh Soni",
    role: "Outreach Lead",
    band: "Non-tech",
    photo: "team/t5.jpeg",
    intro:
      "Connects the club to other campuses, sponsors, and the AWS student network. If a partner shows up on stage, Rohan probably wrote the first mail.",
    position: "Outreach Lead, AWS Student Builder Club · GITS",
    field: "Partnerships and campus community",
    qualifications: ["B.Tech ECE, GITS", "Campus ambassador programs"],
    achievements: [
      "Opened conversations with four Rajasthan campuses for Community Day",
      "Grew the club WhatsApp community past 600 members",
      "Ran referral contests that filled workshop seats in 48 hours",
    ],
    experience: [
      {
        title: "Outreach Lead",
        org: "AWS Student Builder Club, GITS",
        period: "2025 — present",
      },
    ],
    technologies: ["Canva", "LinkedIn", "Mail", "Notion"],
    fact: "Has a spreadsheet of every chai stall near GITS ranked by “speaker recovery time.”",
    linkedin: "https://www.linkedin.com/in/daksh-soni-2945a4328/",
  },
  {
    id: "design",
    name: "Gunjal Gupta",
    role: "Design Lead",
    band: "Non-tech",
    photo: "/team/t6.jpeg",
    intro:
      "Owns the visual language of the club — posters, stage slides, socials, and the look of Community Day. Makes AWS orange feel like Udaipur.",
    position: "Design Lead, AWS Student Builder Club · GITS",
    field: "Brand, experience, and visual storytelling",
    qualifications: [
      "B.Tech CSE, GITS",
      "UI foundations and motion design coursework",
    ],
    achievements: [
      "Designed the club identity used across campus posters",
      "Built the Community Day visual system",
      "Ran a meme contest that outperformed paid reach",
    ],
    experience: [
      {
        title: "Design Lead",
        org: "AWS Student Builder Club, GITS",
        period: "2025 — present",
      },
    ],
    technologies: ["Figma", "Photoshop", "After Effects", "Canva"],
    fact: "Collects Mehrangarh skyline photos at golden hour and sneakily puts them in slide decks.",
    linkedin: "https://www.linkedin.com/in/gunjal-gupta-a4028825b/",
  },
  {
    id: "operations",
    name: "Chanchal Mali",
    role: "Operations Lead",
    band: "Non-tech",
    photo: "/team/t7.jpeg",
    intro:
      "Makes the day actually run — rooms, check-in, volunteers, AV, and the boring details nobody notices until they fail. They rarely fail.",
    position: "Operations Lead, AWS Student Builder Club · GITS",
    field: "Event operations and volunteer systems",
    qualifications: ["B.Tech ME, GITS", "Event operations workshops"],
    achievements: [
      "Ran check-in for the largest workshop the club has hosted",
      "Built the volunteer roster used across events",
      "Cut setup time in the auditorium by half with a written runbook",
    ],
    experience: [
      {
        title: "Operations Lead",
        org: "AWS Student Builder Club, GITS",
        period: "2025 — present",
      },
      {
        title: "Stage volunteer",
        org: "College annual function",
        period: "2023 — 2024",
      },
    ],
    technologies: ["Google Workspace", "Notion", "Excel", "Slack"],
    fact: "Carries spare HDMI adapters the way some people carry pens.",
    linkedin: "https://www.linkedin.com/in/chanchal-mali-23221a329/",
  },
];

export const teamBands = [
  { id: "Leadership", caption: "Captain & Vice Captain" },
  { id: "Tech", caption: "Tech leads" },
  { id: "Non-tech", caption: "Non-tech leads" },
];

// Home page gallery
export const GALLERY_CATEGORIES = [
  "All",
  "Workshops",
  "Hackathons",
  "Talks",
  "Community",
  "Labs",
];

export const galleryPhotos = [
  {
    id: "g-01",
    aspect: "4 / 3",
    src: "/gallery/image1.jpeg",
    title: "Prize Distribution",
    event: "Cloud Kickoff Workshop",
    category: "Workshops",
    date: "2025-08-16",
    location: "Innovation Block, GITS",
    photographer: "Club Media Team",
    featured: true,
  },
  {
    id: "g-02",
    aspect: "1599 / 899",
    src: "/gallery/image2.jpeg",
    title: "Prize Distribution",
    event: "Architecture Lab",
    category: "Workshops",
    date: "2025-09-04",
    location: "Lab 3, GITS",
    photographer: "Club Media Team",
    featured: true,
  },
  {
    id: "g-03",
    aspect: "4 / 3",
    src: "/gallery/image3.jpeg",
    title: "Introduction to Serverless",
    event: "Cloud Resilience Hackathon",
    category: "Workshop",
    date: "2025-10-12",
    location: "Main Auditorium Foyer",
    photographer: "Club Media Team",
    featured: true,
  },
  {
    id: "g-04",
    aspect: "4 / 3",
    src: "/gallery/image4.jpeg",
    title: "Keynote lighting the hall",
    event: "Expert Lecture: IAM & Security",
    category: "Talks",
    date: "2025-11-08",
    location: "Main Auditorium, GITS",
    photographer: "Club Media Team",
    featured: true,
  },
  {
    id: "g-05",
    aspect: "4 / 3",
    src: "/gallery/image5.jpeg",
    title: "Squad shipping a lab together",
    event: "Hands-on Lambda Lab",
    category: "Labs",
    date: "2026-01-18",
    location: "Innovation Block, GITS",
    photographer: "Club Media Team",
    featured: true,
  },
  {
    id: "g-06",
    aspect: "4 / 3",
    src: "/gallery/image6.jpeg",
    title: "Community meetup after hours",
    event: "Builder Circle",
    category: "Community",
    date: "2026-02-07",
    location: "Campus courtyard",
    photographer: "Club Media Team",
    featured: true,
  },
  {
    id: "g-07",
    aspect: "4 / 3",
    src: "/gallery/image7.jpeg",
    title: "Mentors walking the floor",
    event: "Office Hours",
    category: "Community",
    date: "2026-02-21",
    location: "Club room, GITS",
    photographer: "Club Media Team",
    featured: false,
  },
  {
    id: "g-08",
    aspect: "3 / 4",
    src: "/gallery/image8.jpeg",
    title: "Certificate wrap-up",
    event: "Cloud Kickoff Workshop",
    category: "Workshops",
    date: "2025-08-16",
    location: "Innovation Block, GITS",
    photographer: "Club Media Team",
    featured: true,
  },
  {
    id: "g-09",
    aspect: "3 / 4",
    src: "/gallery/image9.jpeg",
    title: "Demo day on the big screen",
    event: "Cloud Resilience Hackathon",
    category: "Hackathons",
    date: "2025-10-12",
    location: "Main Auditorium, GITS",
    photographer: "Club Media Team",
    featured: false,
  },
  {
    id: "g-10",
    aspect: "3 / 4",
    src: "/gallery/image10.jpeg",
    title: "Laptops, cables, and cloud consoles",
    event: "Hands-on Lambda Lab",
    category: "Labs",
    date: "2026-01-18",
    location: "Lab 3, GITS",
    photographer: "Club Media Team",
    featured: true,
  },
  {
    id: "g-11",
    aspect: "4 / 3",
    src: "/gallery/image11.jpeg",
    title: "Q&A with the visiting speaker",
    event: "Expert Lecture: IAM & Security",
    category: "Talks",
    date: "2025-11-08",
    location: "Main Auditorium, GITS",
    photographer: "Club Media Team",
    featured: false,
  },
  {
    id: "g-12",
    aspect: "3 / 4",
    src: "/gallery/image12.jpeg",
    title: "Group photo after the session",
    event: "Builder Circle",
    category: "Community",
    date: "2026-02-07",
    location: "Campus courtyard",
    photographer: "Club Media Team",
    featured: true,
  },
  {
    id: "g-13",
    aspect: "3 / 4",
    src: "/gallery/image13.jpeg",
    title: "Team huddle before the pitch",
    event: "Cloud Resilience Hackathon",
    category: "Hackathons",
    date: "2025-10-13",
    location: "Innovation Block, GITS",
    photographer: "Club Media Team",
    featured: false,
  },
  {
    id: "g-14",
    aspect: "4 / 3",
    src: "/gallery/image14.jpeg",
    title: "Live architecture walkthrough",
    event: "Architecture Lab",
    category: "Labs",
    date: "2025-09-04",
    location: "Lab 3, GITS",
    photographer: "Club Media Team",
    featured: false,
  },
  {
    id: "g-15",
    aspect: "520 / 347",
    src: "/gallery/image15.jpeg",
    title: "Hall filling up for Community Day prep",
    event: "Community Day Planning Meet",
    category: "Talks",
    date: "2026-03-02",
    location: "Main Auditorium, GITS",
    photographer: "Club Media Team",
    featured: false,
  },
  {
    id: "g-16",
    aspect: "520 / 347",
    src: "/gallery/image16.jpeg",
    title: "New members induction",
    event: "Builder Circle",
    category: "Community",
    date: "2026-03-14",
    location: "Club room, GITS",
    photographer: "Club Media Team",
    featured: false,
  },
  {
    id: "g-17",
    aspect: "520 / 347",
    src: "/gallery/image17.jpeg",
    title: "Gallery photo 17",
    event: "Community Gallery",
    category: "Community",
    date: "2026-10-10",
    location: "GITS",
    photographer: "Club Media Team",
    featured: false,
  },
  {
    id: "g-18",
    aspect: "3 / 2",
    src: "/gallery/image18.jpeg",
    title: "Gallery photo 18",
    event: "Community Gallery",
    category: "Community",
    date: "2026-10-10",
    location: "GITS",
    photographer: "Club Media Team",
    featured: false,
  },
  {
    id: "g-19",
    aspect: "520 / 347",
    src: "/gallery/image19.jpeg",
    title: "Gallery photo 19",
    event: "Community Gallery",
    category: "Community",
    date: "2026-10-10",
    location: "GITS",
    photographer: "Club Media Team",
    featured: false,
  },
  {
    id: "g-20",
    aspect: "85 / 107",
    src: "/gallery/image20.jpeg",
    title: "Gallery photo 20",
    event: "Community Gallery",
    category: "Community",
    date: "2026-10-10",
    location: "GITS",
    photographer: "Club Media Team",
    featured: false,
  },
  {
    id: "g-21",
    aspect: "3 / 2",
    src: "/gallery/image21.jpeg",
    title: "Gallery photo 21",
    event: "Community Gallery",
    category: "Community",
    date: "2026-10-10",
    location: "GITS",
    photographer: "Club Media Team",
    featured: false,
  },
];

export const galleryEvents = [...new Set(galleryPhotos.map((p) => p.event))];

export function featuredGalleryPhotos(limit = 9) {
  return galleryPhotos.filter((p) => p.featured).slice(0, limit);
}

export function filterGallery(
  photos,
  { category = "All", event = "All", sort = "newest" } = {},
) {
  let next = photos;
  if (category && category !== "All") {
    next = next.filter((p) => p.category === category);
  }
  if (event && event !== "All") {
    next = next.filter((p) => p.event === event);
  }
  next = [...next].sort((a, b) => {
    const da = new Date(a.date).getTime();
    const db = new Date(b.date).getTime();
    return sort === "oldest" ? da - db : db - da;
  });
  return next;
}

// Home page events
export const sampleEvents = [
  {
    id: "evt-community-day",
    title: "AWS Student Community Day — Udaipur",
    description:
      "A full-day gathering of student builders, speakers, and AWS community at 3rd Space Udaipur. Talks, labs, contests, and a Student-hosted Community Day.",
    date: "31/10/2026",
    time: "10:00 AM – 4:00 PM",
    location: "3rd Space Udaipur",
    speaker: "AWS Student Builder Group, GITS",
    image: "cd.jpeg",
    category: "AWS Community Day",
    difficulty: "All levels",
    format: "Offline",
    certificate: true,
    registrationOpen: true,
    registrationWidget: true,
    capacity: 150,
    registeredCount: 0,
    countdownTarget: "2026-10-31T09:00:00",
  },
];

export const whatWeDoEvents = [
  {
    title: "Introduction to Cloud Computing",
    description:
      "Learn the fundamentals of cloud computing, how cloud services work, and where they are used.",
    image: "whatwedo1.jpg",
    category: "Cloud Fundamentals",
  },
  {
    title: "Expert Talk on Cloud Computing",
    description:
      "Featuring Akshat S, a software engineering specialist focused on observability and DevOps, with AWS SLA and CLP certifications and previous experience at MBRDI.",
    image: "whatwedo2.jpeg",
    category: "Expert Talk",
  },
  {
    title: "AWS Free Tier Account Creation",
    description:
      "Get started with AWS by learning how to create an account and use the AWS Free Tier.",
    image:
      "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=1200&auto=format&fit=crop",
    category: "Getting Started",
  },
  {
    title: "Static Website Hosting on AWS S3",
    description:
      "Learn the core steps for hosting a static website with Amazon S3.",
    image: "whatwedo4.jpeg",
    category: "Hands-on Lab",
  },
  {
    title: "Introduction to Serverless Computing",
    description:
      "Explore how serverless computing works and when it can be useful.",
    image: "whatwedo5.jpeg",
    category: "Cloud Concepts",
  },
];
